name: SFTP Deploy

on:
  push:
    branches: [ main, master ]  
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup Node.js for Vue.js frontend
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    # Setup PHP for Laravel backend
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
        tools: composer:v2

    # Build Vue.js frontend
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    # Prepare Laravel backend
    - name: Install backend dependencies
      working-directory: ./backend
      run: composer install --optimize-autoloader --no-dev

    - name: Create Laravel environment file
      working-directory: ./backend
      run: |
        cp .env.example .env
        php artisan key:generate

    # Deploy frontend to web
    - name: Deploy Frontend via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        local_path: './frontend/dist/*'
        remote_path: '/animalsciencedays.org/web/'
        sftp_only: true

    # Deploy backend to API
    - name: Deploy Backend via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        local_path: './backend/'
        remote_path: '/animalsciencedays.org/sub/api/'
        sftp_only: true
        args: '--exclude=.git* --exclude=node_modules --exclude=tests --exclude=.phpunit.result.cache --exclude=.DS_Store --exclude=.vscode --exclude=storage/logs --exclude=.env.example --exclude=README.md --exclude=package*.json'

    # Set Laravel permissions via SFTP
    - name: Set Laravel permissions
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        script: |
          chmod -R 755 /animalsciencedays.org/sub/api/storage
          chmod -R 755 /animalsciencedays.org/sub/api/bootstrap/cache
